version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thangvu
      MYSQL_USER: thangvu2325
      MYSQL_PASSWORD: thangvu2325
    volumes:
      - ./data/mysql:/var/lib/nestjsApp
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./data/cache:/var/lib/nestjsApp
