version: '3.3'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - '29030:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thangvu
      MYSQL_USER: thangvu2325
      MYSQL_PASSWORD: thangvu2325
      MYSQL_ROOT_HOST: '%' 
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - my-sql-data:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-data:/var/lib/redis
volumes:
  my-sql-data:
  redis-data:
